export const PRODUCTION_NAME = 'FatWeb'
export const STORAGE_TOKEN_KEY = 'JWT_TOKEN'
export const STORAGE_USER_INFO_KEY = 'USER_INFO'
export const COLOR_ORIGIN = 'white'
export const COLOR_PRODUCTION = '#4E47BB'
export const COLOR_MAIN = COLOR_PRODUCTION
export const COLOR_SECONDARY = '#BAB8E5'
export const COLOR_ERROR = '#FF4D4F'
export const COLOR_ERROR_SECONDARY = '#FF7875'
export const COLOR_BLUE = '#1677FF'
export const COLOR_ACTIVE = '#EBECFD'
export const COLOR_BACKGROUND = '#F5F5F5'
export const COLOR_TOP = 'rgba(234,46,13,0.85)'
export const COLOR_FONT_MAIN = '#4D4D4D'
export const COLOR_FONT_SECONDARY = '#9E9E9E'
export const COLOR_FOCUS = '#DDDDDD'
export const SIZE_ICON_XS = '16px'
export const SIZE_ICON_SM = '20px'
export const SIZE_ICON_MD = '24px'
export const SIZE_ICON_LG = '32px'
export const SIZE_ICON_XL = '64px'

/**
 * Response code
 */
export const SYSTEM_OK = 10000
export const SYSTEM_LOGIN_SUCCESS = 10020
export const SYSTEM_PASSWORD_CHANGE_SUCCESS = 10021
export const SYSTEM_LOGOUT_SUCCESS = 10022
export const SYSTEM_TOKEN_RENEW_SUCCESS = 10023
export const SYSTEM_UNAUTHORIZED = 10030
export const SYSTEM_USERNAME_NOT_FOUND = 10031
export const SYSTEM_ACCESS_DENIED = 10032
export const SYSTEM_USER_DISABLE = 10033
export const SYSTEM_LOGIN_USERNAME_PASSWORD_ERROR = 10034
export const SYSTEM_OLD_PASSWORD_NOT_MATCH = 10035
export const SYSTEM_LOGOUT_FAILED = 10036
export const SYSTEM_TOKEN_ILLEGAL = 10037
export const SYSTEM_TOKEN_HAS_EXPIRED = 10038
export const SYSTEM_REQUEST_ILLEGAL = 10040
export const SYSTEM_ARGUMENT_NOT_VALID = 10041
export const SYSTEM_ERROR = 10050
export const SYSTEM_TIMEOUT = 10051

export const DATABASE_SELECT_SUCCESS = 20000
export const DATABASE_SELECT_FAILED = 20005
export const DATABASE_INSERT_SUCCESS = 20010
export const DATABASE_INSERT_FAILED = 20015
export const DATABASE_UPDATE_SUCCESS = 20020
export const DATABASE_UPDATE_FILED = 20025
export const DATABASE_DELETE_SUCCESS = 20030
export const DATABASE_DELETE_FILED = 20035
export const DATABASE_EXECUTE_ERROR = 20040
export const DATABASE_DUPLICATE_KEY = 20045
