export const URL_LOGIN = '/login'
export const URL_TOKEN = '/token'
export const URL_LOGOUT = '/logout'
export const URL_SYS_LOG = '/system/log'
export const URL_SYS_USER_INFO = '/system/user/info'
export const URL_SYS_USER = '/system/user'
export const URL_SYS_ROLE = '/system/role'
export const URL_SYS_POWER_LIST = '/system/power/list'
export const URL_SYS_ROLE_LIST = '/system/role/list'
export const URL_SYS_GROUP = '/system/group'
export const URL_SYS_GROUP_LIST = '/system/group/list'

export const URL_API_V1_AVATAR_RANDOM_BASE64 = '/api/v1/avatar/base64'
