export const URL_API_LOGIN = '/login'
export const URL_API_TOKEN = '/token'
export const URL_API_LOGOUT = '/logout'
export const URL_API_SYS_LOG = '/system/log'
export const URL_API_SYS_USER_INFO = '/system/user/info'
export const URL_API_SYS_USER = '/system/user'
export const URL_API_SYS_ROLE = '/system/role'
export const URL_API_SYS_POWER = '/system/power'
